title: Pico
description: A stupidly simple, blazing fast, flat file CMS.
base_url: http://picocms.org
gh_project_url: https://github.com/picocms/Pico
gh_project_branch: master
gh_pages_url: https://github.com/picocms/Pico
gh_pages_branch: gh-pages
collections:
- docs
- plugin-dev
- download
- cookbook
permalink: pretty
